# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: La Valdi
email: claumavaldivieso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jesus Freak and Front End developer, HTML, CSS, Javascript and more
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lavaldi.me" # the base hostname & protocol for your site
twitter_username: lavaldi_
github_username: lavaldi
google_username: ClaudiaValdiviesoCastillo

permalink: /:categories/:title

links:
  - title: about
    url: /about-me/
  - title: work
    url: /work/
  - title: jesus freak
    url: /jesus-freak/
  - title: learn
    url: /learn/

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jemoji
